# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arac_kiralama_odevi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1248, 987)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color:rgb(246, 134, 86);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #ffffff;\n"
"    color: rgb(81,72,65);\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color:rgb(81,72,65);    \n"
"    background: #ffffff;\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"    background: #ffffff;\n"
"}\n"
"QDateTimeEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QDateEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QLabel {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-style: inset;\n"
"    border-color: rgb(150,150,150);\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style: solid;\n"
"    border-radius:8px;\n"
"    border-width:1px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"     background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"      background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-color: rgb(255,150,60);\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid;\n"
"      border-color: rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox::tab {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 110, 381, 221))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:rgb(0, 0, 0)")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 341, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 0, 0)")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lneTCKimlikNo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneTCKimlikNo.setStyleSheet("color:rgb(207, 207, 207);\n"
"\n"
"")
        self.lneTCKimlikNo.setObjectName("lneTCKimlikNo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lneTCKimlikNo)
        self.lneAd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneAd.setObjectName("lneAd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneAd)
        self.lneSoyad = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneSoyad.setObjectName("lneSoyad")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneSoyad)
        self.lneTelefonNumarasi = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneTelefonNumarasi.setObjectName("lneTelefonNumarasi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lneTelefonNumarasi)
        self.lneEPosta = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneEPosta.setObjectName("lneEPosta")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lneEPosta)
        self.dteDogumTarihi = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.dteDogumTarihi.setObjectName("dteDogumTarihi")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dteDogumTarihi)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(60, 340, 381, 241))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 341, 201))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cmbVites = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cmbVites.setObjectName("cmbVites")
        self.cmbVites.addItem("")
        self.cmbVites.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbVites)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cmbAracSinifi = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cmbAracSinifi.setObjectName("cmbAracSinifi")
        self.cmbAracSinifi.addItem("")
        self.cmbAracSinifi.addItem("")
        self.cmbAracSinifi.addItem("")
        self.cmbAracSinifi.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbAracSinifi)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cmbYakit = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cmbYakit.setObjectName("cmbYakit")
        self.cmbYakit.addItem("")
        self.cmbYakit.addItem("")
        self.cmbYakit.addItem("")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbYakit)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cmbAracMarka = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cmbAracMarka.setObjectName("cmbAracMarka")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.cmbAracMarka.addItem("")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbAracMarka)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.cmbKMLimit = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cmbKMLimit.setObjectName("cmbKMLimit")
        self.cmbKMLimit.addItem("")
        self.cmbKMLimit.addItem("")
        self.cmbKMLimit.addItem("")
        self.cmbKMLimit.addItem("")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbKMLimit)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.cmbFiyatAraligi = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.cmbFiyatAraligi.setObjectName("cmbFiyatAraligi")
        self.cmbFiyatAraligi.addItem("")
        self.cmbFiyatAraligi.addItem("")
        self.cmbFiyatAraligi.addItem("")
        self.cmbFiyatAraligi.addItem("")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmbFiyatAraligi)
        self.rdbBebekKoltugu = QtWidgets.QRadioButton(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdbBebekKoltugu.setFont(font)
        self.rdbBebekKoltugu.setObjectName("rdbBebekKoltugu")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.rdbBebekKoltugu)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 660, 811, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblwMusteriBilgi = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblwMusteriBilgi.setStyleSheet("color:rgb(141, 141, 141)")
        self.tblwMusteriBilgi.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblwMusteriBilgi.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblwMusteriBilgi.setRowCount(100)
        self.tblwMusteriBilgi.setColumnCount(19)
        self.tblwMusteriBilgi.setObjectName("tblwMusteriBilgi")
        self.verticalLayout_2.addWidget(self.tblwMusteriBilgi)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(60, 40, 261, 51))
        self.label_15.setStyleSheet("color:rgb(71, 71, 71);\n"
"background-image:url(:/images/saydam.png);\n"
"font: 16pt \"Gill Sans Ultra Bold\";")
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(70, 600, 131, 31))
        self.label_18.setStyleSheet("color:rgb(71, 71, 71);\n"
"font: 12pt \"Gill Sans Ultra Bold\";\n"
"background-image: url(:/images/saydam.png);")
        self.label_18.setObjectName("label_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 120, 581, 341))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color:rgb(0, 0, 0)")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 545, 307))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.dteTeslimAlisTarih = QtWidgets.QDateTimeEdit(self.formLayoutWidget_2)
        self.dteTeslimAlisTarih.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteTeslimAlisTarih.setObjectName("dteTeslimAlisTarih")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dteTeslimAlisTarih)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dteTeslimEdisTarih = QtWidgets.QDateTimeEdit(self.formLayoutWidget_2)
        self.dteTeslimEdisTarih.setDate(QtCore.QDate(2024, 1, 1))
        self.dteTeslimEdisTarih.setObjectName("dteTeslimEdisTarih")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dteTeslimEdisTarih)
        self.chkFarkliYer = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chkFarkliYer.setFont(font)
        self.chkFarkliYer.setObjectName("chkFarkliYer")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.chkFarkliYer)
        self.chkKurumsalArac = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chkKurumsalArac.setFont(font)
        self.chkKurumsalArac.setObjectName("chkKurumsalArac")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.chkKurumsalArac)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.txtAlis = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.txtAlis.setObjectName("txtAlis")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtAlis)
        self.txtEdis = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.txtEdis.setObjectName("txtEdis")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtEdis)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(910, 660, 162, 247))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnEkle = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnEkle.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnEkle.setFont(font)
        self.btnEkle.setMouseTracking(False)
        self.btnEkle.setAcceptDrops(False)
        self.btnEkle.setToolTip("")
        self.btnEkle.setAutoFillBackground(False)
        self.btnEkle.setStyleSheet("color:rgb(71, 71, 71);\n"
"font: 10pt \"Gill Sans Ultra Bold\";")
        self.btnEkle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btnEkle.setCheckable(False)
        self.btnEkle.setAutoRepeat(False)
        self.btnEkle.setAutoExclusive(False)
        self.btnEkle.setAutoDefault(False)
        self.btnEkle.setDefault(False)
        self.btnEkle.setFlat(False)
        self.btnEkle.setObjectName("btnEkle")
        self.verticalLayout_3.addWidget(self.btnEkle)
        self.btnSil = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnSil.setFont(font)
        self.btnSil.setStyleSheet("color:rgb(71, 71, 71);\n"
"font: 10pt \"Gill Sans Ultra Bold\";")
        self.btnSil.setObjectName("btnSil")
        self.verticalLayout_3.addWidget(self.btnSil)
        self.btnGuncelle = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setStyleSheet("color:rgb(71, 71, 71);\n"
"font: 10pt \"Gill Sans Ultra Bold\";")
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.verticalLayout_3.addWidget(self.btnGuncelle)
        self.btnListele = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnListele.setFont(font)
        self.btnListele.setStyleSheet("color:rgb(71, 71, 71);\n"
"font: 10pt \"Gill Sans Ultra Bold\";")
        self.btnListele.setObjectName("btnListele")
        self.verticalLayout_3.addWidget(self.btnListele)
        self.btncikis = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btncikis.setFont(font)
        self.btncikis.setStyleSheet("color:rgb(71, 71, 71);\n"
"font: 10pt \"Gill Sans Ultra Bold\";")
        self.btncikis.setObjectName("btncikis")
        self.verticalLayout_3.addWidget(self.btncikis)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1248, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmbVites.setCurrentIndex(-1)
        self.cmbAracSinifi.setCurrentIndex(-1)
        self.cmbYakit.setCurrentIndex(-1)
        self.cmbAracMarka.setCurrentIndex(-1)
        self.cmbKMLimit.setCurrentIndex(-1)
        self.cmbFiyatAraligi.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Sürücü Bilgileri"))
        self.label.setText(_translate("MainWindow", "TC Kimlik No:"))
        self.label_2.setText(_translate("MainWindow", "Ad:"))
        self.label_3.setText(_translate("MainWindow", "Soyad:"))
        self.label_4.setText(_translate("MainWindow", "Telefon Numarası:"))
        self.label_5.setText(_translate("MainWindow", "E-Posta:"))
        self.label_6.setText(_translate("MainWindow", "Doğum Tarihi:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Araç Özellik"))
        self.label_11.setText(_translate("MainWindow", "Vites:"))
        self.cmbVites.setItemText(0, _translate("MainWindow", "Manuel"))
        self.cmbVites.setItemText(1, _translate("MainWindow", "Otomatik"))
        self.label_12.setText(_translate("MainWindow", "Araç Sınıfı:"))
        self.cmbAracSinifi.setItemText(0, _translate("MainWindow", "Ekonomik"))
        self.cmbAracSinifi.setItemText(1, _translate("MainWindow", "Orta"))
        self.cmbAracSinifi.setItemText(2, _translate("MainWindow", "Lüks"))
        self.cmbAracSinifi.setItemText(3, _translate("MainWindow", "Minibüs"))
        self.label_13.setText(_translate("MainWindow", "Yakıt:"))
        self.cmbYakit.setItemText(0, _translate("MainWindow", "Dizel"))
        self.cmbYakit.setItemText(1, _translate("MainWindow", "Benzin"))
        self.cmbYakit.setItemText(2, _translate("MainWindow", "Hibrit"))
        self.label_14.setText(_translate("MainWindow", "Araç Marka:"))
        self.cmbAracMarka.setItemText(0, _translate("MainWindow", "Audi"))
        self.cmbAracMarka.setItemText(1, _translate("MainWindow", "Bmw"))
        self.cmbAracMarka.setItemText(2, _translate("MainWindow", "Citroen"))
        self.cmbAracMarka.setItemText(3, _translate("MainWindow", "Dacia"))
        self.cmbAracMarka.setItemText(4, _translate("MainWindow", "Fiat"))
        self.cmbAracMarka.setItemText(5, _translate("MainWindow", "Ford"))
        self.cmbAracMarka.setItemText(6, _translate("MainWindow", "Hyundai"))
        self.cmbAracMarka.setItemText(7, _translate("MainWindow", "Jeep"))
        self.cmbAracMarka.setItemText(8, _translate("MainWindow", "Mercedes"))
        self.cmbAracMarka.setItemText(9, _translate("MainWindow", "Nissan"))
        self.cmbAracMarka.setItemText(10, _translate("MainWindow", "Opel"))
        self.cmbAracMarka.setItemText(11, _translate("MainWindow", "Range Rover"))
        self.cmbAracMarka.setItemText(12, _translate("MainWindow", "Renault"))
        self.cmbAracMarka.setItemText(13, _translate("MainWindow", "Toyota"))
        self.cmbAracMarka.setItemText(14, _translate("MainWindow", "Volkswagen"))
        self.label_16.setText(_translate("MainWindow", "Kilometre Limit:"))
        self.cmbKMLimit.setItemText(0, _translate("MainWindow", "0-1000km"))
        self.cmbKMLimit.setItemText(1, _translate("MainWindow", "1000-2000km"))
        self.cmbKMLimit.setItemText(2, _translate("MainWindow", "2000-4000km"))
        self.cmbKMLimit.setItemText(3, _translate("MainWindow", "4000-6000km"))
        self.label_17.setText(_translate("MainWindow", "Günlük Fiyat Aralığı:"))
        self.cmbFiyatAraligi.setItemText(0, _translate("MainWindow", "TRY1000-TRY2000"))
        self.cmbFiyatAraligi.setItemText(1, _translate("MainWindow", "TRY2000-TRY4000"))
        self.cmbFiyatAraligi.setItemText(2, _translate("MainWindow", "TRY4000-TRY6000"))
        self.cmbFiyatAraligi.setItemText(3, _translate("MainWindow", "TRY6000+"))
        self.rdbBebekKoltugu.setText(_translate("MainWindow", "Bebek koltuğu"))
        self.label_15.setText(_translate("MainWindow", "SONDURAK"))
        self.label_18.setText(_translate("MainWindow", "ÜYELER"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Rezervasyon"))
        self.label_7.setText(_translate("MainWindow", "Teslim Alış Tarihi ve Saati:"))
        self.label_8.setText(_translate("MainWindow", "Teslim Ediş Tarihi ve Saati:"))
        self.chkFarkliYer.setText(_translate("MainWindow", "Araç farklı yerde teslim edilecek."))
        self.chkKurumsalArac.setText(_translate("MainWindow", "Kurumsal araç kiralama."))
        self.label_9.setText(_translate("MainWindow", "Teslim Alış Yeri:"))
        self.label_10.setText(_translate("MainWindow", "Teslim Ediş Yeri:"))
        self.btnEkle.setText(_translate("MainWindow", "KAYIT EKLE"))
        self.btnSil.setText(_translate("MainWindow", "KAYIT SiL"))
        self.btnGuncelle.setText(_translate("MainWindow", "GÜNCELLE"))
        self.btnListele.setText(_translate("MainWindow", "KAYIT LİSTELE"))
        self.btncikis.setText(_translate("MainWindow", "ÇIKIŞ"))
